#  1- Olist E-Commerca Date Analysis Project.

##### Date Cleaning & Preprocessing

In [145]:
import pandas as pd
import numpy as np
import os

# 2- Read file

In [4]:
customers = pd.read_csv("olist_customers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_payments = pd.read_csv("olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
category_translation = pd.read_csv("product_category_name_translation.csv")

# Date Profiling

In [55]:
tables = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in tables.items():
    print("=" * 60)
    print(name)
    print("Rows & Columns:", df.shape)
    print("Duplicates:", df.duplicated().sum())
    print("Missing Values:", df.isnull().sum().sum())

============================================================
customers
Rows & Columns: (99441, 5)
Duplicates: 0
Missing Values: 0
============================================================
geolocation
Rows & Columns: (1000163, 5)
Duplicates: 261831
Missing Values: 0
============================================================
order_items
Rows & Columns: (112650, 7)
Duplicates: 0
Missing Values: 0
============================================================
order_payments
Rows & Columns: (103886, 5)
Duplicates: 0
Missing Values: 0
============================================================
order_reviews
Rows & Columns: (99224, 7)
Duplicates: 0
Missing Values: 145903
============================================================
orders
Rows & Columns: (99441, 8)
Duplicates: 0
Missing Values: 4908
============================================================
products
Rows & Columns: (32951, 9)
Duplicates: 0
Missing Values: 2448
============================================================
sellers
Rows & Columns: (3095, 4)
Duplicates: 0
Missing Values: 0
============================================================
category_translation
Rows & Columns: (71, 2)
Duplicates: 0
Missing Values: 0

# Import_Order-table

In [6]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [7]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [8]:
orders.describe(include="all")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-04-11 10:48:14,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-08 23:38:46,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

# 2-Missing Values

In [9]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

# Date Time

In [56]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

# order_status

In [18]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [19]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

# Duplicates_Order ID

In [58]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [59]:
orders["order_id"].nunique()

99441

In [60]:
orders_clean = orders.copy()

# Impossible Date

In [20]:
orders[
    orders["order_delivered_customer_date"] <
    orders["order_purchase_timestamp"]
].shape

(0, 8)

In [21]:
orders[
    orders["order_delivered_carrier_date"] <
    orders["order_purchase_timestamp"]
].shape

(166, 8)

In [22]:
orders[
    orders["order_estimated_delivery_date"] <
    orders["order_purchase_timestamp"]
].shape

(0, 8)

# check space And name Column

In [61]:
orders.columns = orders.columns.str.strip()

In [62]:
orders["order_id"].isnull().sum()

np.int64(0)

In [63]:
orders_clean = orders.copy()

# Order_Item

In [27]:
order_items.shape

(112650, 7)

In [28]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [29]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [30]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [31]:
order_items.duplicated().sum()

np.int64(0)

# Check IDs

In [32]:
print("Order IDs:", order_items["order_id"].nunique())
print("Product IDs:", order_items["product_id"].nunique())
print("Seller IDs:", order_items["seller_id"].nunique())

Order IDs: 98666
Product IDs: 32951
Seller IDs: 3095

In [33]:
order_items["order_item_id"].value_counts().head(10)

order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
Name: count, dtype: int64

# Date conversion

In [34]:
order_items["shipping_limit_date"] = pd.to_datetime(
    order_items["shipping_limit_date"],
    errors="coerce"
)

In [35]:
order_items.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

#  Check Value

In [36]:
order_items[["price", "freight_value"]].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

# Check Negative

In [37]:
print("Negative price:", (order_items["price"] < 0).sum())
print("Negative freight:", (order_items["freight_value"] < 0).sum())

Negative price: 0
Negative freight: 0

# nulls

In [38]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [39]:
order_items_clean = order_items.copy()

# Order_Payments

In [40]:
order_payments.shape

(103886, 5)

In [41]:
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [42]:
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [43]:
order_payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [45]:
order_payments.duplicated().sum()

np.int64(0)

#  Check_ Payment_type

In [46]:
order_payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

#  Check Installments

In [47]:
order_payments["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [48]:
(order_payments["payment_installments"] < 1).sum()

np.int64(2)

#  CHECK_Payment Value

In [49]:
order_payments["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

# nagtive

In [50]:
(order_payments["payment_value"] < 0).sum()

np.int64(0)

# Check IDS

In [51]:
order_payments["order_id"].isnull().sum()

np.int64(0)

In [52]:
order_payments["order_id"].duplicated().sum()

np.int64(4446)

# CHECK CLEANING

In [53]:
order_payments["payment_type"] = order_payments["payment_type"].str.strip().str.lower()

In [54]:
order_payments_clean = order_payments.copy()

# ORDER_View

In [64]:
order_reviews.shape

(99224, 7)

In [1]:
order_reviews.head()

NameError: name 'order_reviews' is not defined

In [67]:
order_reviews.info()order_reviews.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [68]:
order_reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [69]:
order_reviews.duplicated().sum()

np.int64(0)

# Review Score

In [70]:
order_reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

# review date

In [74]:
review_date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in review_date_columns:
    order_reviews[col] = pd.to_datetime(
        order_reviews[col],
        errors="coerce"
    )

In [75]:
text_columns = [
    "review_comment_title",
    "review_comment_message"
]

for col in text_columns:
    order_reviews[col] = order_reviews[col].str.strip()

In [76]:
text_columns = [
    "review_comment_title",
    "review_comment_message"
]

for col in text_columns:
    order_reviews[col] = order_reviews[col].str.strip()

# Products

In [77]:
products.shape

(32951, 9)

In [78]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [79]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [80]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

# Check Product Id

In [81]:
products["product_id"].isnull().sum()

np.int64(0)

In [82]:
products["product_id"].duplicated().sum()

np.int64(0)

In [83]:
products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [84]:
numeric_product_columns = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

for col in numeric_product_columns:
    print(col, "negative values:", (products[col] < 0).sum())

product_name_lenght negative values: 0
product_description_lenght negative values: 0
product_photos_qty negative values: 0
product_weight_g negative values: 0
product_length_cm negative values: 0
product_height_cm negative values: 0
product_width_cm negative values: 0

# clean name catgory

In [85]:
products["product_category_name"] = (
    products["product_category_name"]
    .str.strip()
    .str.lower()
)

In [86]:
products_clean = products.copy()

# CUSTOMERS

In [87]:
customers.shape

(99441, 5)

In [88]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [89]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [90]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [92]:
customers.duplicated().sum()

np.int64(0)

# IDS

In [93]:
print("customer_id duplicates:",
      customers["customer_id"].duplicated().sum())

print("customer_unique_id duplicates:",
      customers["customer_unique_id"].duplicated().sum())

customer_id duplicates: 0
customer_unique_id duplicates: 3345

In [94]:
customers["customer_city"] = customers["customer_city"].str.strip().str.lower()
customers["customer_state"] = customers["customer_state"].str.strip().str.upper()

In [95]:
customers_clean = customers.copy()

# SELLERS

In [96]:
sellers.shape

(3095, 4)

In [97]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [98]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [99]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [100]:
sellers.duplicated().sum()

np.int64(0)

# Seller ID

In [101]:
sellers["seller_id"].isnull().sum()

np.int64(0)

In [102]:
sellers["seller_id"].duplicated().sum()

np.int64(0)

In [103]:
sellers["seller_city"] = sellers["seller_city"].str.strip().str.lower()
sellers["seller_state"] = sellers["seller_state"].str.strip().str.upper()

In [104]:
sellers_clean = sellers.copy()

# category_translation

In [105]:
category_translation.shape

(71, 2)

In [106]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [107]:
category_translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [108]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [109]:
category_translation.duplicated().sum()

np.int64(0)

In [110]:
for col in category_translation.columns:
    category_translation[col] = (
        category_translation[col]
        .str.strip()
        .str.lower()
    )

In [111]:
category_translation_clean = category_translation.copy()

# geolocation

In [112]:
geolocation.shape

(1000163, 5)

In [113]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [114]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [126]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [127]:
geolocation.duplicated().sum()

np.int64(261831)

# Check_Zib_code

In [129]:
geolocation["geolocation_zip_code_prefix"].duplicated().sum()

np.int64(981148)

In [130]:
geolocation["geolocation_zip_code_prefix"].nunique()

19015

#  check_Longitue , latitude.

In [131]:
geolocation[[
    "geolocation_lat",
    "geolocation_lng"
]].describe()

       geolocation_lat  geolocation_lng
count     1.000163e+06     1.000163e+06
mean     -2.117615e+01    -4.639054e+01
std       5.715866e+00     4.269748e+00
min      -3.660537e+01    -1.014668e+02
25%      -2.360355e+01    -4.857317e+01
50%      -2.291938e+01    -4.663788e+01
75%      -1.997962e+01    -4.376771e+01
max       4.506593e+01     1.211054e+02

In [132]:
geolocation[[
    "geolocation_lat",
    "geolocation_lng"
]].isnull().sum()

geolocation_lat    0
geolocation_lng    0
dtype: int64

In [133]:
geolocation["geolocation_city"] = (
    geolocation["geolocation_city"]
    .str.strip()
    .str.lower()
)

geolocation["geolocation_state"] = (
    geolocation["geolocation_state"]
    .str.strip()
    .str.upper()
)

# CLEAN Deplicates

In [135]:
geolocation_clean = geolocation.drop_duplicates().copy()

In [136]:
print("Original:", geolocation.shape)
print("Cleaned:", geolocation_clean.shape)

Original: (1000163, 5)
Cleaned: (738332, 5)

# Check End ALL Table

In [137]:
clean_tables = {
    "customers": customers_clean,
    "geolocation": geolocation_clean,
    "order_items": order_items_clean,
    "order_payments": order_payments_clean,
    "order_reviews": order_reviews_clean,
    "orders": orders_clean,
    "products": products_clean,
    "sellers": sellers_clean,
    "category_translation": category_translation_clean
}

for name, df in clean_tables.items():
    print("=" * 50)
    print(name)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("Nulls:", df.isnull().sum().sum())
    print("Duplicates:", df.duplicated().sum())

==================================================
customers
Rows: 99441
Columns: 5
Nulls: 0
Duplicates: 0
==================================================
geolocation
Rows: 738332
Columns: 5
Nulls: 0
Duplicates: 0
==================================================
order_items
Rows: 112650
Columns: 7
Nulls: 0
Duplicates: 0
==================================================
order_payments
Rows: 103886
Columns: 5
Nulls: 0
Duplicates: 0
==================================================
order_reviews
Rows: 99224
Columns: 7
Nulls: 145903
Duplicates: 0
==================================================
orders
Rows: 99441
Columns: 8
Nulls: 4908
Duplicates: 0
==================================================
products
Rows: 32951
Columns: 9
Nulls: 2448
Duplicates: 0
==================================================
sellers
Rows: 3095
Columns: 4
Nulls: 0
Duplicates: 0
==================================================
category_translation
Rows: 71
Columns: 2
Nulls: 0
Duplicates: 0

# Cleaned CSVs

In [139]:
for name, df in clean_tables.items():
    df.to_csv(f"cleaned_{name}.csv", index=False)

# Check that file

In [140]:
import os

[f for f in os.listdir() if f.startswith("cleaned_") and f.endswith(".csv")]

['cleaned_category_translation.csv',
 'cleaned_customers.csv',
 'cleaned_geolocation.csv',
 'cleaned_orders.csv',
 'cleaned_order_items.csv',
 'cleaned_order_payments.csv',
 'cleaned_order_reviews.csv',
 'cleaned_products.csv',
 'cleaned_sellers.csv']

In [141]:
# ==============================
# FINAL DATA QUALITY CHECK
# ==============================

# 1. Check all tables
for name, df in clean_tables.items():
    print("=" * 60)
    print(name)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("Missing Values:", df.isnull().sum().sum())
    print("Duplicate Rows:", df.duplicated().sum())


# 2. Check Orders -> Customers
missing_customers = ~orders_clean["customer_id"].isin(
    customers_clean["customer_id"]
)

print("\nOrders with missing customer:", missing_customers.sum())


# 3. Check Order Items -> Orders
missing_orders = ~order_items_clean["order_id"].isin(
    orders_clean["order_id"]
)

print("Order Items with missing order:", missing_orders.sum())


# 4. Check Order Items -> Products
missing_products = ~order_items_clean["product_id"].isin(
    products_clean["product_id"]
)

print("Order Items with missing product:", missing_products.sum())


# 5. Check Order Items -> Sellers
missing_sellers = ~order_items_clean["seller_id"].isin(
    sellers_clean["seller_id"]
)

print("Order Items with missing seller:", missing_sellers.sum())


# 6. Check Payments -> Orders
missing_payment_orders = ~order_payments_clean["order_id"].isin(
    orders_clean["order_id"]
)

print("Payments with missing order:", missing_payment_orders.sum())


# 7. Check Reviews -> Orders
missing_review_orders = ~order_reviews_clean["order_id"].isin(
    orders_clean["order_id"]
)

print("Reviews with missing order:", missing_review_orders.sum())

============================================================
customers
Rows: 99441
Columns: 5
Missing Values: 0
Duplicate Rows: 0
============================================================
geolocation
Rows: 738332
Columns: 5
Missing Values: 0
Duplicate Rows: 0
============================================================
order_items
Rows: 112650
Columns: 7
Missing Values: 0
Duplicate Rows: 0
============================================================
order_payments
Rows: 103886
Columns: 5
Missing Values: 0
Duplicate Rows: 0
============================================================
order_reviews
Rows: 99224
Columns: 7
Missing Values: 145903
Duplicate Rows: 0
============================================================
orders
Rows: 99441
Columns: 8
Missing Values: 4908
Duplicate Rows: 0
============================================================
products
Rows: 32951
Columns: 9
Missing Values: 2448
Duplicate Rows: 0
============================================================
sellers
Rows: 3095
Columns: 4
Missing Values: 0
Duplicate Rows: 0
============================================================
category_translation
Rows: 71
Columns: 2
Missing Values: 0
Duplicate Rows: 0

Orders with missing customer: 0
Order Items with missing order: 0
Order Items with missing product: 0
Order Items with missing seller: 0
Payments with missing order: 0
Reviews with missing order: 0

In [142]:
# ==============================
# EXPORT CLEANED DATA
# ==============================

for name, df in clean_tables.items():
    df.to_csv(f"cleaned_{name}.csv", index=False)

print("All cleaned files exported successfully!")

All cleaned files exported successfully!

In [143]:
[f for f in os.listdir() if f.startswith("cleaned_")]

['cleaned_category_translation.csv',
 'cleaned_customers.csv',
 'cleaned_geolocation.csv',
 'cleaned_orders.csv',
 'cleaned_order_items.csv',
 'cleaned_order_payments.csv',
 'cleaned_order_reviews.csv',
 'cleaned_products.csv',
 'cleaned_sellers.csv']